version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:14.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_prisma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      DATABASE_HOST: 127.0.0.1
    restart: always

volumes:
  postgres:
